# Generated by Django 5.1.15 on 2026-06-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ")),
                (
                    "expected_personnel",
                    models.PositiveIntegerField(
                        default=0, verbose_name="غذای پیش\u200cبینی کارکنان"
                    ),
                ),
                (
                    "expected_guests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="غذای پیش\u200cبینی مهمان\u200cها"
                    ),
                ),
                (
                    "total_ordered",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کل سفارش"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه نهار روزانه",
                "verbose_name_plural": "برنامه\u200cهای نهار روزانه",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MealToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="تاریخ")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("personnel", "پرسنل"), ("guest", "مهمان")],
                        max_length=10,
                        verbose_name="نوع گیرنده",
                    ),
                ),
                (
                    "token_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="کد ژتون"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "صادر شده"),
                            ("consumed", "مصرف شده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="issued",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان صدور"
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مصرف"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "consumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumed_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول ثبت مصرف",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_tokens",
                        to="guests.guest",
                        verbose_name="مهمان",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صادرکننده",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_tokens",
                        to="people.personnel",
                        verbose_name="پرسنل",
                    ),
                ),
            ],
            options={
                "verbose_name": "ژتون غذا",
                "verbose_name_plural": "ژتون\u200cهای غذا",
                "ordering": ["-date", "-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="تاریخ")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "تلاش صدور تکراری"),
                            ("consume", "تلاش مصرف نامعتبر"),
                        ],
                        max_length=10,
                        verbose_name="نوع تلاش",
                    ),
                ),
                (
                    "recipient_label",
                    models.CharField(blank=True, max_length=150, verbose_name="گیرنده"),
                ),
                ("message", models.CharField(max_length=255, verbose_name="پیام")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_attempts",
                        to="meals.mealtoken",
                        verbose_name="ژتون مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تلاش تکراری / مغایرت",
                "verbose_name_plural": "تلاش\u200cهای تکراری / مغایرت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="mealtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", "canceled"), _negated=True),
                    ("personnel__isnull", False),
                ),
                fields=("date", "personnel"),
                name="unique_personnel_token_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", "canceled"), _negated=True),
                    ("guest__isnull", False),
                ),
                fields=("date", "guest"),
                name="unique_guest_token_per_day",
            ),
        ),
    ]
