# Generated by Django 5.1.15 on 2026-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="org_unit",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="واحد سازمانی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "مدیر سیستم"),
                    ("reception", "پذیرش / نگهبانی"),
                    ("restaurant", "مسئول رستوران"),
                    ("protocol", "واحد تشریفات"),
                    ("host", "مدیر واحد / میزبان"),
                    ("office_manager", "مدیر اداری"),
                    ("supply", "واحد تأمین"),
                    ("report_viewer", "مدیر گزارش\u200cگیر"),
                ],
                default="host",
                max_length=20,
                verbose_name="نقش سازمانی",
            ),
        ),
    ]
