# Generated by Django 5.1.15 on 2026-06-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CateringItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام قلم"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "عدد"),
                            ("kilo", "کیلو"),
                            ("pack", "بسته"),
                            ("person", "نفر"),
                        ],
                        default="piece",
                        max_length=10,
                        verbose_name="واحد شمارش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم پذیرایی",
                "verbose_name_plural": "اقلام پذیرایی",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CateringRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="عنوان درخواست"),
                ),
                (
                    "catering_date",
                    models.DateField(db_index=True, verbose_name="تاریخ پذیرایی"),
                ),
                (
                    "prepare_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت آماده\u200cسازی"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="محل پذیرایی"
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("meeting", "جلسه"),
                            ("visit", "بازدید"),
                            ("vip", "مهمان ویژه"),
                            ("interview", "مصاحبه"),
                            ("ceremony", "مراسم"),
                            ("other", "سایر"),
                        ],
                        default="meeting",
                        max_length=15,
                        verbose_name="نوع مناسبت",
                    ),
                ),
                (
                    "headcount",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد نفرات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "ثبت\u200cشده"),
                            ("preparing", "در حال آماده\u200cسازی"),
                            ("ready", "آماده"),
                            ("delivered", "تحویل\u200cشده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="registered",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catering_requests",
                        to="people.personnel",
                        verbose_name="درخواست\u200cدهنده / میزبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست پذیرایی",
                "verbose_name_plural": "درخواست\u200cهای پذیرایی",
                "ordering": ["-catering_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CateringRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=8, verbose_name="مقدار"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="catering.cateringitem",
                        verbose_name="قلم پذیرایی",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catering.cateringrequest",
                        verbose_name="درخواست پذیرایی",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم درخواست پذیرایی",
                "verbose_name_plural": "اقلام درخواست پذیرایی",
                "ordering": ["item__name"],
            },
        ),
    ]
