# Generated by Django 5.1.15 on 2026-06-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catering", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cateringrequest",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت پایان"),
        ),
        migrations.AddField(
            model_name="cateringrequest",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت شروع"),
        ),
        migrations.AddField(
            model_name="cateringrequestitem",
            name="needs_purchase",
            field=models.BooleanField(default=False, verbose_name="نیاز به خرید"),
        ),
        migrations.AddField(
            model_name="cateringrequestitem",
            name="purchase_status",
            field=models.CharField(
                choices=[("pending", "در انتظار تهیه"), ("purchased", "تهیه شد")],
                default="pending",
                max_length=10,
                verbose_name="وضعیت تهیه",
            ),
        ),
        migrations.AddField(
            model_name="cateringrequestitem",
            name="purchased_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان تهیه"),
        ),
        migrations.AddField(
            model_name="cateringrequestitem",
            name="purchased_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تهیه\u200cکننده",
            ),
        ),
        migrations.CreateModel(
            name="CateringLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="نام محل"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ظرفیت"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "محل پذیرایی",
                "verbose_name_plural": "محل\u200cهای پذیرایی",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="cateringrequest",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="catering.cateringlocation",
                verbose_name="محل پذیرایی",
            ),
        ),
    ]
