# Generated by Django 5.1.15 on 2026-06-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=80, verbose_name="نام خانوادگی"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="شرکت / سازمان"
                    ),
                ),
                (
                    "guest_type",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("contractor", "پیمانکار"),
                            ("supplier", "تأمین\u200cکننده"),
                            ("visitor", "بازدیدکننده"),
                            ("vip", "مهمان ویژه"),
                            ("other", "سایر"),
                        ],
                        default="visitor",
                        max_length=20,
                        verbose_name="نوع مهمان",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="تاریخ مراجعه")),
                (
                    "expected_entry_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت ورود تقریبی"
                    ),
                ),
                (
                    "expected_exit_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت خروج تقریبی"
                    ),
                ),
                (
                    "needs_lunch",
                    models.BooleanField(default=False, verbose_name="نیاز به نهار"),
                ),
                (
                    "needs_catering",
                    models.BooleanField(
                        default=False, verbose_name="نیاز به پذیرایی ویژه"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "ثبت\u200cشده"),
                            ("entered", "وارد شده"),
                            ("exited", "خارج شده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="registered",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "host_personnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_guests",
                        to="people.personnel",
                        verbose_name="میزبان داخلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمان",
                "verbose_name_plural": "مهمان\u200cها",
                "ordering": ["-visit_date", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="GuestCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان کارت")),
                (
                    "card_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد کارت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "آزاد"),
                            ("assigned", "تخصیص داده شده"),
                            ("inactive", "غیرفعال"),
                        ],
                        default="free",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "کارت مهمان",
                "verbose_name_plural": "کارت\u200cهای مهمان",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CardAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("assigned_date", models.DateField(verbose_name="تاریخ تخصیص")),
                (
                    "delivered_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت تحویل کارت"
                    ),
                ),
                (
                    "returned_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت برگشت کارت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("returned", "برگشت داده شده"),
                            ("lost", "مفقود شده"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تحویل\u200cدهنده",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_assignments",
                        to="guests.guest",
                        verbose_name="مهمان",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="guests.guestcard",
                        verbose_name="کارت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص کارت",
                "verbose_name_plural": "تخصیص کارت\u200cها",
                "ordering": ["-assigned_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("card",),
                        name="unique_active_assignment_per_card",
                    )
                ],
            },
        ),
    ]
