# Generated by Django 5.1.15 on 2026-06-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تأیید"),
                    ("approved", "تأییدشده"),
                    ("rejected", "ردشده"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="وضعیت تأیید",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان تأیید/رد"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_guests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأییدکننده",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="review_note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="توضیح تأیید/رد"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت\u200cشده"),
                    ("entered", "وارد شده"),
                    ("exited", "خارج شده"),
                    ("canceled", "لغو شده"),
                ],
                default="registered",
                max_length=15,
                verbose_name="وضعیت حضور",
            ),
        ),
    ]
