# Generated by Django 5.1.15 on 2026-06-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catering",
            "0002_cateringrequest_end_time_cateringrequest_start_time_and_more",
        ),
        ("guests", "0002_guest_approval_status_guest_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="stationing_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stationed_guests",
                to="catering.cateringlocation",
                verbose_name="محل استقرار",
            ),
        ),
    ]
