# Generated by Django 5.1.15 on 2026-06-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=80, verbose_name="نام خانوادگی"),
                ),
                (
                    "personnel_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="کد پرسنلی"
                    ),
                ),
                (
                    "org_unit",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="واحد سازمانی"
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("employee", "کارمند"),
                            ("service", "نیروی خدماتی"),
                            ("contractor", "پیمانکار ثابت"),
                            ("driver", "راننده"),
                            ("other", "سایر"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="نوع فرد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "card_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="شناسه کارت / تردد",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسنل",
                "verbose_name_plural": "پرسنل",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
