# Generated by Django 5.1.15 on 2026-06-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="شناسه دستگاه"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام دستگاه"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("org_entrance", "ورودی سازمان"),
                            ("restaurant", "رستوران"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع دستگاه",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستگاه تردد",
                "verbose_name_plural": "دستگاه\u200cهای تردد",
                "ordering": ["device_id"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("org_entrance", "ورودی سازمان"),
                            ("restaurant", "رستوران"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="نوع دستگاه",
                    ),
                ),
                (
                    "card_or_fingerprint",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        verbose_name="شناسه کارت / اثر انگشت",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="تاریخ و ساعت ثبت")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("entry", "ورود"),
                            ("exit", "خروج"),
                            ("meal_request", "درخواست غذا"),
                        ],
                        default="entry",
                        max_length=15,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "پردازش\u200cنشده"),
                            ("processed", "پردازش\u200cشده"),
                            ("error", "خطا"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت پردازش",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, null=True, verbose_name="داده خام"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="attendance.attendancedevice",
                        verbose_name="دستگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد تردد",
                "verbose_name_plural": "رویدادهای تردد",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
